### PR TITLE
Fix inaccurate renderer nameing

### LINKED ISSUE #895: Rendering functions should document expected `&[RenderElement]` z-order
Current documentation for `DamageTrackedRenderer` states the following:

> Render this output

During rendering I would usually expect back to front element order, however this function expects front to back order.
While users might still run into and notice this issue by doing it wrong the first time, there should be documentation reassuring them what the correct element order is meant to be.

CC @cmeissl

### PR DESCRIPTION
**Pull request by cmeissl**
The naming of `DamageTrackedRenderer` implies that it is a renderer, which it is not. Fix this inaccuracy by renaming:

- `DamageTrackedRenderer` -> `OutputDamageTracker`
- `DamageTracker` -> `DamageBag`
- `DamageTrackerSnapshot` -> `DamageSnapshot`

This also documents the expected z-order of elements.

fixes #895

### CODE REVIEW

File: src/backend/renderer/damage.rs [hunk 1]
```diff
@@ -254,17 +262,17 @@ impl TryInto<(Size<i32, Physical>, Scale<f64>, Transform)> for DamageTrackedRend
...
+    mode: OutputDamageTrackerMode,
     last_state: RendererState,
     span: tracing::Span,
 }
 
-/// Errors thrown by [`DamageTrackedRenderer::render_output`]
+/// Errors thrown by [`OutputDamageTracker::render_output`]
 #[derive(thiserror::Error)]
-pub enum DamageTrackedRendererError<R: Renderer> {
+pub enum OutputDamageTrackerError<R: Renderer> {
```
Comment (Drakulix) [inline src/backend/renderer/damage.rs:275]: Actually, while we are at it (sorry for bringing this up only just now)... I would vastly prefer to just name this `Error` and solve conflicts by renaming the import in other modules.

This is not C, we don't have to prefix everything with the module-name or similar.

**Review by Drakulix — COMMENTED** [review]
Looks good! Really liking the new names much better. Just a small nitpick...

File: src/backend/renderer/damage.rs (hunk 1 above)
Comment (i509VCB) [reply src/backend/renderer/damage.rs:275]: I'd agree with this, but then I ask that question about the rest of smithay. Should Gles2Renderer be gles2::Renderer or do we want the explicit name. Some of the reexports add a prefix (gbm::Device exported as GbmDevice)

Comment (cmeissl) [reply src/backend/renderer/damage.rs:275]: I am fine with changing it, but we should stay consistent. So if we change it here we should also it everywhere else. Not sure if gradually, starting with this one, or changing all at once is better. But I lean towards making that change gradually. This could potentially affect a big surface of the API. No one likes to review such big PRs and it might take a bit so the potential for rebase conflicts is pretty high.

Comment (Drakulix) [reply src/backend/renderer/damage.rs:275]: Right and at least for error types I think we are semi-consistent in the sense, that we prefer shorter names.
Also I don't think for main structs like the `Gles2Renderer` or the `OutputDamageTracker` renaming really makes sense. For the Gles2Renderer it is particularly problematic given the `Renderer`-trait just one module above.

Comment (cmeissl) [reply src/backend/renderer/damage.rs]: renamed to `Error`

**Review by Drakulix — APPROVED** [review]
