### PR TITLE
anvil: properly document logind support

### LINKED ISSUE #139: Missing systemd default support / warning message for legacy sessions
After launch `./anvil --tty-udev` the background appears and the mouse pointer in the upper left corner, but everything hangs, the cursor does not move, Caps Lock does not work, CTRL-ALT-F1-12 does not work, you can exit this state only by pressing the reset button or ALT-SysRq-R
distro: Arch Linux
kernel: 5.0.13-arch1-1-ARCH
video: intel hd graphics
log:
> May 14 18:14:14.074 INFO Starting anvil on a tty using udev
May 14 18:14:14.076 INFO Listening on wayland socket, name: wayland-0
May 14 18:14:14.076 INFO Trying to create tty session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.076 INFO Running from tty: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.076 DEBG Opening device: "/dev/dri/card0", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.076 INFO DrmDevice initializing, smithay_module: backend_drm
May 14 18:14:14.076 WARN Unable to become drm master, assuming unpriviledged mode, smithay_module: backend_drm
May 14 18:14:14.098 DEBG Creating gbm device, smithay_module: backend_gbm
May 14 18:14:14.105 DEBG Creating egl context from device, smithay_module: backend_egl
May 14 18:14:14.105 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.107 DEBG EGL No-Display Extensions: ["EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_EXT_platform_base", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_EXT_platform_wayland", "EGL_EXT_platform_x11", "EGL_MESA_platform_gbm", "EGL_MESA_platform_surfaceless"], smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.107 INFO EGL Initialized, smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.107 INFO EGL Version: (1, 4), smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.107 INFO EGL Extensions: ["EGL_ANDROID_blob_cache", "EGL_ANDROID_native_fence_sync", "EGL_EXT_buffer_age", "EGL_EXT_create_context_robustness", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_IMG_context_priority", "EGL_KHR_config_attribs", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image", "EGL_KHR_image_base", "EGL_KHR_image_pixmap", "EGL_KHR_no_config_context", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_image_dma_buf_export", "EGL_WL_bind_wayland_display", ""], smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.107 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.108 DEBG EGL context successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.109 INFO EGL context created, smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.131 INFO Connected: DisplayPort
May 14 18:14:14.131 INFO Initializing EglSurface, smithay_module: backend_egl
May 14 18:14:14.132 INFO Initializing GbmSurface, smithay_module: backend_gbm
May 14 18:14:14.152 DEBG EGL surface successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
May 14 18:14:14.161 DEBG Importing cursor, crtc: Handle(47), smithay_module: backend_gbm
May 14 18:14:14.162 DEBG Commiting new state, crtc: Handle(47), smithay_module: backend_gbm
May 14 18:14:14.162 DEBG Setting screen, crtc: Handle(47), smithay_module: backend_drm
May 14 18:14:14.170 INFO Initializing a xkbcommon handler with keymap query, options: None, variant: , layout: , model: , rules: , smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
May 14 18:14:14.172 INFO Loaded Keymap, name: English (US), smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
May 14 18:14:14.173 INFO Creating new wl_output, name: Drm, smithay_module: output_handler
May 14 18:14:14.176 DEBG Opening device: "/dev/input/event2", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.176 DEBG Opening device: "/dev/input/event9", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.176 DEBG Opening device: "/dev/input/event1", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.177 DEBG Opening device: "/dev/input/event0", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.177 DEBG Opening device: "/dev/input/event3", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.177 DEBG Opening device: "/dev/input/event4", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.177 DEBG Opening device: "/dev/input/event5", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.178 DEBG Opening device: "/dev/input/event6", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.178 DEBG Opening device: "/dev/input/event10", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.178 DEBG Opening device: "/dev/input/event11", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.178 DEBG Opening device: "/dev/input/event12", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.178 DEBG Opening device: "/dev/input/event8", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.179 DEBG Opening device: "/dev/input/event7", component: session, vt: 2, session_type: direct/vt, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
May 14 18:14:14.179 INFO Initializing a libinput backend, smithay_module: backend_libinput
May 14 18:14:14.179 INFO New input handler set, smithay_module: backend_libinput

### PR DESCRIPTION
**Pull request by vberger**
Fixes #139

### CODE REVIEW

File: anvil/build.rs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+use std::env::var;
+
+fn main() {
+    if !var("CARGO_FEATURE_LOGIND").ok().is_some() {
+        println!("cargo:warning=You are compiling anvil without login support.");
```
Comment (Drakulix) [inline anvil/build.rs]: login**d** support

Comment (vberger) [reply anvil/build.rs]: Thanks, corrected. :sweat_smile:
